name: flutter_designer_tools
description: A simple package to bring UI designs to life in Flutter.
version: 0.0.1
author: thearthurdev<arthurdelords@gmail.com>
homepage: https://github.com/thearthurdev/designer_tools

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_color_picker: ^1.0.7
  flutter_material_color_picker: ^1.0.5
  provider: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
