name: flutter_designer_tools
description: A simple package to bring UI designs to life in Flutter.
version: 0.0.1
author: thearthurdev<arthurdelords@gmail.com>
homepage: https://github.com/thearthurdev/designer_tools

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.5.1
  flutter_colorpicker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/designer_tools_transparent.png
    - assets/mockup.png
